
CREATE TABLE IF NOT EXISTS MEMBER_INFO (
    MEMBER_ID BIGINT PRIMARY KEY,
    MEMBER_BALANCE SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS MEMBER_BALANCE_HISTORY (
    MEMBER_ID BIGINT PRIMARY KEY,
    INDE_AMOUNT SMALLINT NOT NULL,
    TOTAL_BALANCE SMALLINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,

    CONSTRAINT FK_MEMBER_INFO
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER_INFO (MEMBER_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_INFO (
    PRODUCT_ID BIGINT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT_OPTION (
    PRODUCT_OPTION_ID BIGINT PRIMARY KEY,
    PRODUCT_ID BIGINT,
    OPTION_NAME VARCHAR(20),

    CONSTRAINT FK_PRODUCT_INFO_PRODUCT_OPTION
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT_INFO (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_STOCK(
    PRODUCT_ID BIGINT PRIMARY KEY,
    PRODUCT_OPTION_ID BIGINT,
    PRODUCT_QUANTITY SMALLINT NOT NULL,

    CONSTRAINT FK_PRODUCT_INFO_STOCK
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT_INFO (PRODUCT_ID),
    CONSTRAINT FK_PRODUCT_INFO_PRODUCT_STOCK
        FOREIGN KEY (PRODUCT_OPTION_ID)
        REFERENCES PRODUCT_OPTION (PRODUCT_OPTION_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_HISTORY(
    PRODUCT_ID BIGINT PRIMARY KEY,
    INDE_AMOUNT SMALLINT NOT NULL,
    TOTAL_QUANTITY SMALLINT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_PRODUCT_INFO_HISTORY
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT_INFO (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_INFO (
    ORDER_ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT,
    PRODUCT_LIST VARCHAR(200) NOT NULL,
    OPTION_LIST VARCHAR(200) NOT NULL,
    QUANTITY_LIST VARCHAR(200) NOT NULL,

    CONSTRAINT FK_MEMBER_INFO_ORDER_INFO
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER_INFO (MEMBER_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_HISTORY (
    ORDER_ID BIGINT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_OPTION_ID BIGINT NOT NULL,
    QUANTITY SMALLINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,

    CONSTRAINT FK_ORDER_INFO_ORDER_HISTORY
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDER_INFO (ORDER_ID),
    CONSTRAINT FK_MEMBER_INFO_ORDER_HISTORY
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER_INFO (MEMBER_ID),
    CONSTRAINT FK_PRODUCT_INFO
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT_INFO (PRODUCT_ID),
    CONSTRAINT FK_PRODUCT_OPTION_ORDER_HISTORY
        FOREIGN KEY (PRODUCT_OPTION_ID)
        REFERENCES PRODUCT_OPTION (PRODUCT_OPTION_ID)
);

CREATE TABLE IF NOT EXISTS SHOPPING_CART (
    PRODUCT_ID BIGINT PRIMARY KEY ,
    PRODUCT_OPTION_ID VARCHAR(10),
    QUANTITY SMALLINT,

    CONSTRAINT FK_PRODUCT_ID_CART
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT_INFO (PRODUCT_ID),
    CONSTRAINT FK_PRODUCT_OPTION_SHOPPING_CART
        FOREIGN KEY (PRODUCT_OPTION_ID)
        REFERENCES PRODUCT_OPTION (PRODUCT_OPTION_ID)
);

CREATE TABLE IF NOT EXISTS PAYMENT_HISTORY (
    MEMBER_ID BIGINT,
    ORDER_ID BIGINT,
    PAYMENT_AMOUNT SMALLINT,

    CONSTRAINT FK_MEMBER_INFO_PAYMENT_HISTORY
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER_INFO (MEMBER_ID),
    CONSTRAINT FK_ORDER_INFO_PAYMENT_HISTORY
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDER_INFO (ORDER_ID)
);